newIssueWelcomeComment: >
  Congrats on creating your first Issue in the C0D1NG Organization! ğŸ‰

newPRWelcomeComment: >
  Congrats on making your first Pull Request in the C0D1NG Organization! ğŸ¥³

firstPRMergeComment: >
  Congrats on merging your first pull request! We are proud of you! ğŸ¤—
  We invited you to join our organization please check your email. ğŸš€
